version: "3.8"
services:
    website:
        container_name: app_ws
        build: ./backend
        ports:
            - 8000:80
        volumes:
            - ./backend/src:/var/www/html
        depends_on:
            - db
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
    db:
        platform: linux/x86_64
        image: mysql:8.0
        container_name: app_db
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 12345
        volumes:
            - mysqldata:/var/lib/mysql
            - ./dump:/docker-entrypoint-initdb.d

volumes:
    mysqldata:
